### ISSUE TITLE
Getting django.template.exceptions.TemplateDoesNotExist for serviceworker.js

### ISSUE THREAD

**Issue by pnaylor** [silviolleite/django-pwa#1]
This doesn't make much sense to me. Getting django.template.exceptions.TemplateDoesNotExist for serviceworker.js which is in my static/js folder. Not sure what would make Django even think this is a template.

Any suggestions would be appreciated. Thanks!

**Comment by silviolleite** [comment]
Hello @pnaylor, you must put your custom serviceworker.js in a template directory, and then point at it using the `PWA_SERVICE_WORKER_PATH` variable in your setting (`PWA_APP_FETCH_URL` is passed through).

`PWA_SERVICE_WORKER_PATH = 'your_app/serviceworker.js'`

It is a template because the view `ServiceWorker` class extends `TemplateView` to get the context.

**Comment by pnaylor** [comment]
Thank you, putting it in a template directory seems to have resolved this.
