### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by Khoding** [silviolleite/django-pwa#89]
Hello, so just started using the package, and I noticed the url bug so came to check if it had been fixed.

So is it possible to release the fixed version for compatibility with Django 4.0?

**Comment by MahmoodAbuIssa96** [comment]
for some reasons the author doesn't release the new version yet,
the bug for the django 4 already fixed in the master branch 
so for the mean while if you want to use the master code until the release published, you can pip it from the github
replase 
django-pwa==1.0.10
in the requirements.txt with 
git+https://github.com/silviolleite/django-pwa

**Comment by hartungstenio** [comment]
Hello. I will close this issue. Let's focus discussions in #83
